### ISSUE TITLE
process query strings 

### ISSUE THREAD

**Issue by atomGit** [igorlogius/access-url-parts#1]
consider processing query strings

`www.example.com/?this&that`
`www.example.com/?this`
`www.example.com/`
`example.com/`

also, not sure this is doable with the webext API, but i recall other extensions like this where you could click on a url segment right in the address bar to go up a level - no pop-up needed

if that's not possible, and i'm guessing it isn't, you might consider essentially duplicating the url in a single-line pop-up rather than a vertical list - somehow i think that would be more attractive, but that's just me

**Comment by igorlogius** [comment]
> i recall other extensions like this where you could click on a url segment right in the address bar

Sadly as you already guessed, the web-ext api does not allow such url bar manpipulations. 
If that ever changes, i'll gladly take another look into this.
